"""
Two stages:

1. generate_qa_pairs()  — turn raw doc chunks into instruction/response pairs.
   Raw markdown is NOT training data. A model fine-tuned directly on doc
   paragraphs learns to autocomplete documentation-flavored text, not to
   answer questions. You need actual Q/A or instruction/response pairs,
   generated by prompting a stronger model against each chunk.

2. finetune()  — QLoRA fine-tune a small instruct model on those pairs.

Read the warnings in each function docstring before running this blind.
"""

import json
import time
from pathlib import Path

import anthropic
from datasets import load_dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling,
)
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
import torch
from transformers import BitsAndBytesConfig

CORPUS_FILE = Path("./azure_docs_corpus.jsonl")
QA_FILE = Path("./azure_qa_pairs.jsonl")
BASE_MODEL = "Qwen/Qwen2.5-3B-Instruct"  # swap for Phi-3-mini, Llama-3.2-3B, etc.
OUTPUT_DIR = "./azure-slm-lora"

QA_GEN_PROMPT = """You are generating training data for a technical support model.
Given the Azure documentation excerpt below, write 3 question/answer pairs a
developer or admin would realistically ask. Answers must be fully grounded in
the excerpt — no outside knowledge, no invented CLI flags or numbers not
present in the text. If the excerpt doesn't support a good question, return
fewer than 3 pairs, or none.

Return ONLY a JSON array like:
[{{"question": "...", "answer": "..."}}, ...]

Excerpt (service: {service}, title: {title}):
---
{content}
---
"""


def chunk_content(content: str, max_words: int = 400) -> list[str]:
    words = content.split()
    return [" ".join(words[i:i + max_words]) for i in range(0, len(words), max_words)]


def generate_qa_pairs(limit_docs: int | None = None, max_words_per_chunk: int = 400):
    """
    Cost/time warning: this makes one API call per chunk. A full azure-docs
    pull is tens of thousands of articles -> can be 50k+ chunks. Start with
    limit_docs=200 to sanity check output quality and cost before scaling up.
    """
    client = anthropic.Anthropic()  # expects ANTHROPIC_API_KEY in env
    written = 0

    with CORPUS_FILE.open() as fin, QA_FILE.open("w") as fout:
        for i, line in enumerate(fin):
            if limit_docs and i >= limit_docs:
                break
            doc = json.loads(line)
            for chunk in chunk_content(doc["content"], max_words_per_chunk):
                prompt = QA_GEN_PROMPT.format(
                    service=doc.get("service", ""),
                    title=doc.get("title", ""),
                    content=chunk,
                )
                try:
                    resp = client.messages.create(
                        model="claude-sonnet-4-6",
                        max_tokens=1000,
                        messages=[{"role": "user", "content": prompt}],
                    )
                    text = resp.content[0].text.strip()
                    pairs = json.loads(text)
                except Exception as e:
                    print(f"[qa-gen] skip chunk (doc {i}): {e}")
                    continue

                for p in pairs:
                    if "question" not in p or "answer" not in p:
                        continue
                    fout.write(json.dumps({
                        "instruction": p["question"],
                        "response": p["answer"],
                        "source_doc": doc["path"],
                    }) + "\n")
                    written += 1

                time.sleep(0.3)  # basic rate-limit courtesy

            if i % 50 == 0:
                print(f"[qa-gen] processed {i} docs, {written} pairs so far")

    print(f"[qa-gen] done: {written} QA pairs -> {QA_FILE}")


def format_example(example, tokenizer):
    prompt = (
        f"<|im_start|>system\nYou are an assistant answering questions about "
        f"Microsoft Azure. Answer only from what you know to be accurate; say "
        f"so if you're unsure.<|im_end|>\n"
        f"<|im_start|>user\n{example['instruction']}<|im_end|>\n"
        f"<|im_start|>assistant\n{example['response']}<|im_end|>"
    )
    tokenized = tokenizer(prompt, truncation=True, max_length=1024, padding="max_length")
    tokenized["labels"] = tokenized["input_ids"].copy()
    return tokenized


def finetune():
    """
    QLoRA fine-tune. Needs a GPU with >=16GB VRAM for a 3B model in 4-bit.
    This teaches response FORMAT and grounding behavior on top of the base
    model's existing knowledge — it does not replace RAG for keeping facts
    current. Re-run this only when your QA dataset materially changes;
    don't treat it as a substitute for retrieval at inference time if you
    want up-to-date answers.
    """
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16,
        bnb_4bit_use_double_quant=True,
    )

    tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    model = AutoModelForCausalLM.from_pretrained(
        BASE_MODEL, quantization_config=bnb_config, device_map="auto"
    )
    model = prepare_model_for_kbit_training(model)

    lora_config = LoraConfig(
        r=16,
        lora_alpha=32,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
        lora_dropout=0.05,
        bias="none",
        task_type="CAUSAL_LM",
    )
    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()

    dataset = load_dataset("json", data_files=str(QA_FILE), split="train")
    dataset = dataset.train_test_split(test_size=0.1, seed=42)  # keep a real eval split
    train_ds = dataset["train"].map(lambda ex: format_example(ex, tokenizer))
    eval_ds = dataset["test"].map(lambda ex: format_example(ex, tokenizer))

    args = TrainingArguments(
        output_dir=OUTPUT_DIR,
        per_device_train_batch_size=4,
        gradient_accumulation_steps=4,
        num_train_epochs=3,
        learning_rate=2e-4,
        fp16=False,
        bf16=True,
        logging_steps=20,
        eval_strategy="steps",
        eval_steps=200,
        save_strategy="steps",
        save_steps=200,
        save_total_limit=2,
        load_best_model_at_end=True,
        report_to="none",
    )

    trainer = Trainer(
        model=model,
        args=args,
        train_dataset=train_ds,
        eval_dataset=eval_ds,
        data_collator=DataCollatorForLanguageModeling(tokenizer, mlm=False),
    )

    trainer.train()
    model.save_pretrained(OUTPUT_DIR)
    tokenizer.save_pretrained(OUTPUT_DIR)
    print(f"[finetune] adapter saved to {OUTPUT_DIR}")


if __name__ == "__main__":
    # Step 1 — sanity check on a small slice first.
    generate_qa_pairs(limit_docs=200)

    # Step 2 — only after you've eyeballed azure_qa_pairs.jsonl for quality.
    # finetune()
